### ISSUE TITLE
Server initialisation fails on Mac OS X

### ISSUE THREAD

**Issue by hslatman** [BankingofThings/BoT-Python-SDK#21]
Initialising the server fails due to Python not being able to find libc.so.

Also see this source line: https://github.com/Adam-Langley/pybleno/blob/6a1019add3309cd07bdebc56639839b1a4c148b0/pybleno/hci_socket/BluetoothHCI/BluetoothSocket.py#L28. 

If we're going to need the standard library, we likely need to use the libSystem.dylib.

**Comment by nanchauha** [comment]
Hi @hslatma, unfortunately the BLE library for Python (PyBleno) doesn't work for MacOS and it is a known issue on their side which is yet to be resolved. The work around this for now is to either run the SDK in a VM or directly on the Raspberry Pi.

**Comment by hslatman** [comment]
Tried setting it up with a quick (local) fork of said library. Got a bit further in the process by changing the import to libSystem.dylib for the 'darwin' platform. However, a whole different rabbit hole opened up with support for Bluetooth in Python on Mac 😛. For now, it goes a bit too far to explore potential solutions further (although there seem to be some).

Would it be an option to just turn off the Bluetooth support by supplying an option to the main server.py application?

**Comment by hslatman** [comment]
I created a PR to disable Bluetooth during initialisation of the device: #22.

**Comment by Lokesh-K-Haralakatta** [comment]
Added condition to block execution of BLE if SDK is run on macOS (darwin) even if the Bluetooth is enabled. Also added logic to run bluetooth pairing and resume configuration only if device needs to be paired and activated. The changes are available in the feature branch, needs to be merged to master.
